//
// NetworkQualityServer.h
//
// $Id: //ecodtn/0.1/include/NetworkQualityServer.h#1 $
//
// Library: Ecodtn
// Package: NetworkQualityServer
// Module:  NetworkQualityServer
//
// Definition of the NetworkQualityServer class.
//
// Copyright (c) 2014, Luis Andres Marentes C.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#ifndef NetworkQualityServer_INCLUDED
#define NetworkQualityServer_INCLUDED

#include <Poco/Util/ServerApplication.h>
#include <Poco/Util/Option.h>
#include <Poco/Util/OptionSet.h>
#include <Poco/Util/HelpFormatter.h>

namespace ecodtn
{

namespace net
{
	
	class NetworkQualityServer: public Poco::Util::ServerApplication
	{

	public:

		NetworkQualityServer();
		/// Creates an NetworkQualityServer using ...
		
		~NetworkQualityServer();
		/// Destroy the NetworkQualityServer

	protected:	

		void initialize(Poco::Util::ServerApplication::Application& self);
		/// Initialize the proxy with the corresponding application
		
		void uninitialize();
		
		void defineOptions(Poco::Util::OptionSet& options);
		/// Define the options for the Http Proxy
		
		void handleHelp(const std::string& name, 
						const std::string& value);
		/// Handles the options for executing the http proxy
		
		int main(const std::vector<std::string>& args);
		/// Put to execute the proxy servers with the configuration given

	private:
		bool _helpRequested;
		typedef Poco::AutoPtr<Subsystem> QualitySubsystemPtr;
		typedef std::vector<QualitySubsystemPtr> QualitySubsystemVec;
		QualitySubsystemVec _subsystems;
		

	};

} /// End net namespace

}  /// End ecodtn namespace

#endif // NetworkQualityServer
