//
// RouteManager.h
//
// $Id: //ecodtn/0.1/include/RouteManager.h#1 $
//
// Library: Ecodtn
// Package: Route
// Module:  NetworkQuality
//
// Definition of the RouteManager class.
//
// Copyright (c) 2014, Luis Andres Marentes C.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#ifndef RouteManager_INCLUDED
#define RouteManager_INCLUDED

extern "C" {
  
  #include "route_functions.h"
}

#include <Poco/Net/IPAddress.h>
#include <Poco/Net/NetworkInterface.h>

namespace ecodtn
{

namespace net
{

class RouteManager
{
public:
	RouteManager();
	~RouteManager();
	
	void addRoute(Poco::Net::IPAddress ipaddress, 
				 Poco::Net::NetworkInterface netIntf, 
				 Poco::Net::IPAddress gatewayAddr);
	int existsRoute();
	void deleteRouter(Poco::Net::IPAddress ipaddress, 
					 Poco::Net::NetworkInterface netIntf, 
					 Poco::Net::IPAddress gatewayAddr);

private:
	
	void check_error(int err_result);
	
	struct nl_sock *_sk;
	struct nl_cache *_link_cache;
};

} /// End net namespace

}  /// End ecodtn namespace

#endif // RouteManager_INCLUDED
