//
// tc_functions.c
//
// $Id: //ecodtn/0.1/include/tc_functions.c#1 $
//
// Library: Ecodtn
// Package: TrafficControl
// Module:  NetworkQuality
//
// Definition of the tc_functions class.
//
// Copyright (c) 2014, Luis Andres Marentes C.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#include <stdio.h>
#include <inttypes.h>
#include <netlink/netlink.h>
#include <netlink/route/link.h>
#include <netlink/route/tc.h>
#include <netlink/route/qdisc.h>
#include <netlink/route/class.h>
#include <netlink/route/classifier.h>
#include <netlink/route/cls/u32.h>
#include <netlink/attr.h>
#include <arpa/inet.h>
#include <netlink/route/qdisc/htb.h>
#include <netlink/route/qdisc/sfq.h>
#include <linux/if_ether.h>
#include <netlink/attr.h>
#include "tc_functions.h"

// Build of the qdisk object at the root of the hierarchy
int qdisc_add_root_HTB(struct nl_sock *sock, struct rtnl_link *rtnlLink)
{
   int err = 0;

   if (sock == NULL){
	  printf("sock null");
	  err = -1;
	  return err;
   }
   
   if (rtnlLink == NULL){
	  printf("link null");
	  err = -2;
	  return err;
   }
	   

   uint32_t defaultClass = DEFAULT_CLASS;
  
   printf("Add root Qdisc message 1 \n");

   /* Allocation of a qdisc object */
   struct rtnl_qdisc *qdisc = rtnl_qdisc_alloc();
   if (!qdisc){
	   err = ECODTN_NET_TC_QDISC_ALLOC_ERROR;
	   return err; 
   }

   printf("Add root Qdisc message 2 \n");

   /* Establish the link associated to the class */
   err = rtnl_tc_set_kind(TC_CAST(qdisc), "htb");
   if (err < 0)
   {
       err = ECODTN_NET_TC_QDISC_SETUP_ERROR;
       return err; 
   }
   
   printf("Add root Qdisc message 3 \n");
   
   rtnl_tc_set_link(TC_CAST(qdisc), rtnlLink);
   rtnl_tc_set_parent(TC_CAST(qdisc), TC_H_ROOT);
   rtnl_tc_set_handle(TC_CAST(qdisc), TC_HANDLE(1,0));

   //uint32_t tc_handle = TC_HANDLE(1,0);
   //fprintf(stdout, "tc handle: [%"PRIu32" ]\n",tc_handle );
   // The value of the integer is 65536

   printf("Add root Qdisc message 4 \n");

   /* Set default class for unclassified traffic */
   rtnl_htb_set_defcls(qdisc, TC_HANDLE(1, defaultClass));
   rtnl_htb_set_rate2quantum(qdisc, 1);

   printf("Add root Qdisc message 5 \n");
   
   err = rtnl_qdisc_add(sock, qdisc, NLM_F_CREATE );

   printf("Add root Qdisc message 6 \n");
   /* Free the qdisc object */
   rtnl_qdisc_put(qdisc);

   if (err < 0) {
        err = ECODTN_NET_TC_QDISC_ESTABLISH_ERROR;
        return err;
   }
      
   return ECODTN_NET_TC_SUCCESS;
}


int qdisc_delete_root_HTB(struct nl_sock *sock, struct rtnl_link *rtnlLink )
{
    int err;
    struct rtnl_qdisc *qdisc;

    if (!(qdisc = rtnl_qdisc_alloc())) {
        printf("error on delete Qdisc %d", err);
        err = ECODTN_NET_TC_QDISC_ALLOC_ERROR;
        return err;
    }
	
    rtnl_tc_set_link(TC_CAST(qdisc), rtnlLink);
    rtnl_tc_set_parent(TC_CAST(qdisc), TC_H_ROOT);
    rtnl_tc_set_handle(TC_CAST(qdisc), TC_HANDLE(1,0));

    /* Submit request to kernel and wait for response */
    if ((err = rtnl_qdisc_delete(sock, qdisc))) {
		printf("error on delete Qdisc %d", err);
        err = ECODTN_NET_TC_QDISC_ESTABLISH_ERROR;
		return err;
    }

    /* Return the qdisc object to free memory resources */
    rtnl_qdisc_put(qdisc);
    return ECODTN_NET_TC_SUCCESS;
}



int class_add_HTB_root(struct nl_sock *sock, struct rtnl_link *rtnlLink, 
					   uint64_t rate, uint64_t ceil, 
					   uint32_t burst, uint32_t cburst)
{
    int err;
    struct rtnl_class *class;
    
    //Allocate memory for the HTB class
    if (!(class = rtnl_class_alloc())) {
        printf("Can not allocate class object \n");
        err = ECODTN_NET_TC_CLASS_ALLOC_ERROR;
        return err;
    }
	printf("Add root Class message 1 \n");
    // Assign the link and the class's parent
    rtnl_tc_set_link(TC_CAST(class), rtnlLink);
    rtnl_tc_set_parent(TC_CAST(class), TC_H_ROOT);

    //add the handled for the class class
    rtnl_tc_set_handle(TC_CAST(class), 1);
	printf("Add root Class message 2 \n");

    if ((err = rtnl_tc_set_kind(TC_CAST(class), "htb"))) {
        err = ECODTN_NET_TC_CLASS_SETUP_ERROR;
        return err;
    }
    if (rate) {
       rtnl_htb_set_rate(class, rate);
    }
    if (ceil) {
       rtnl_htb_set_ceil(class, ceil);
    }
    if (burst) {
        rtnl_htb_set_rbuffer(class, burst);
    }
    if (cburst) {
        rtnl_htb_set_cbuffer(class, cburst);
    }
	printf("Add root Class message 3 \n");
    
    /* Submit request to kernel and wait for response */
    if ((err = rtnl_class_add(sock, class, NLM_F_CREATE))) {
        err = ECODTN_NET_TC_CLASS_ESTABLISH_ERROR;
        return err;
    }
    
    // Free the memory allocated for the class structure.
    rtnl_class_put(class);
	printf("Add root Class message 4 \n");
    
    // return Ok.
    return ECODTN_NET_TC_SUCCESS;
}

int class_add_HTB(struct nl_sock *sock, struct rtnl_link *rtnlLink, 
			      uint32_t parentMaj, uint32_t parentMin, 
				  uint32_t childMaj, uint32_t childMin, uint64_t rate, 
				  uint64_t ceil, uint32_t burst, uint32_t cburst, uint32_t prio)
{
    int err;
    struct rtnl_class *class;

    //create a HTB class
    if (!(class = rtnl_class_alloc())) {
        err = ECODTN_NET_TC_CLASS_ALLOC_ERROR;
        return err;
    }
   
    rtnl_tc_set_link(TC_CAST(class), rtnlLink);
    rtnl_tc_set_parent(TC_CAST(class), TC_HANDLE(parentMaj, parentMin));
    rtnl_tc_set_handle(TC_CAST(class), TC_HANDLE(childMaj, childMin));

    if ((err = rtnl_tc_set_kind(TC_CAST(class), "htb"))) {
        err = ECODTN_NET_TC_CLASS_SETUP_ERROR;
        return err;
    }

    //printf("set HTB class prio to %u\n", prio);
    rtnl_htb_set_prio(class, prio);

    if (rate) {
	rtnl_htb_set_rate(class, rate);
    }
    if (ceil) {
	rtnl_htb_set_ceil(class, ceil);
    }
    
    if (burst) {
        rtnl_htb_set_rbuffer(class, burst);
    }
    if (cburst) {
        rtnl_htb_set_cbuffer(class, cburst);
    }
    /* Submit request to kernel and wait for response */
    if ((err = rtnl_class_add(sock, class, NLM_F_CREATE))) {
        err = ECODTN_NET_TC_CLASS_ESTABLISH_ERROR;
        return err;
    }
    rtnl_class_put(class);
    return ECODTN_NET_TC_SUCCESS;
}

int class_delete_HTB(struct nl_sock *sock, struct rtnl_link *rtnlLink, 
			      uint32_t parentMaj, uint32_t parentMin, 
				  uint32_t childMaj, uint32_t childMin )
{
    int err;
    struct rtnl_class *class;

    //create a HTB class
    if (!(class = rtnl_class_alloc())) {
        err = ECODTN_NET_TC_CLASS_ALLOC_ERROR;
        return err;
    }
   
    rtnl_tc_set_link(TC_CAST(class), rtnlLink);
    rtnl_tc_set_parent(TC_CAST(class), TC_HANDLE(parentMaj, parentMin));
    rtnl_tc_set_handle(TC_CAST(class), TC_HANDLE(childMaj, childMin));

    if ((err = rtnl_tc_set_kind(TC_CAST(class), "htb"))) {
        err = ECODTN_NET_TC_CLASS_SETUP_ERROR;
        return err;
    }

    /* Submit request to kernel and wait for response */
    if ((err = rtnl_class_delete(sock, class))) {
        err = ECODTN_NET_TC_CLASS_ESTABLISH_ERROR;
        return err;
    }
    rtnl_class_put(class);
    return ECODTN_NET_TC_SUCCESS;
}

/*
* function that adds a new SFQ qdisc as a leaf for a HTB class
*/
int qdisc_add_SFQ_leaf(struct nl_sock *sock, struct rtnl_link *rtnlLink, 
					   uint32_t parentMaj, uint32_t parentMin, 
					   int quantum, int limit, int perturb)
{
    int err;
    struct rtnl_qdisc *qdisc;

    if (!(qdisc = rtnl_qdisc_alloc())) {
        err = ECODTN_NET_TC_QDISC_ALLOC_ERROR;
        return err;
    }
        
    rtnl_tc_set_link(TC_CAST(qdisc), rtnlLink);
    rtnl_tc_set_parent(TC_CAST(qdisc), TC_HANDLE(parentMaj, parentMin));
    rtnl_tc_set_handle(TC_CAST(qdisc), TC_HANDLE(parentMin,0));

    if ((err = rtnl_tc_set_kind(TC_CAST(qdisc), "sfq"))) {
        err = ECODTN_NET_TC_QDISC_SETUP_ERROR;
        return err;
    }

    if(quantum) {
        rtnl_sfq_set_quantum(qdisc, quantum);
    } else {
        rtnl_sfq_set_quantum(qdisc, 16000); // tc default value
    }
    if(limit) {
        rtnl_sfq_set_limit(qdisc, limit); // default is 127
    }
    if(perturb) {
        rtnl_sfq_set_perturb(qdisc, perturb); // default never perturb the hash
    }

    /* Submit request to kernel and wait for response */
    if ((err = rtnl_qdisc_add(sock, qdisc, NLM_F_CREATE))) {
        err = ECODTN_NET_TC_QDISC_ESTABLISH_ERROR;
		return err;
    }

    /* Return the qdisc object to free memory resources */
    rtnl_qdisc_put(qdisc);
    return ECODTN_NET_TC_SUCCESS;
}


int qdisc_delete_SFQ_leaf(struct nl_sock *sock, struct rtnl_link *rtnlLink, 
					   uint32_t parentMaj, uint32_t parentMin )
{
    int err;
    struct rtnl_qdisc *qdisc;

    if (!(qdisc = rtnl_qdisc_alloc())) {
        err = ECODTN_NET_TC_QDISC_ALLOC_ERROR;
        return err;
    }
        
    rtnl_tc_set_link(TC_CAST(qdisc), rtnlLink);
    rtnl_tc_set_parent(TC_CAST(qdisc), TC_HANDLE(parentMaj, parentMin));
    rtnl_tc_set_handle(TC_CAST(qdisc), TC_HANDLE(parentMin,0));

    if ((err = rtnl_tc_set_kind(TC_CAST(qdisc), "sfq"))) {
        err = ECODTN_NET_TC_QDISC_SETUP_ERROR;
        return err;
    }

    /* Submit request to kernel and wait for response */
    if ((err = rtnl_qdisc_delete(sock, qdisc))) {
        err = ECODTN_NET_TC_QDISC_ESTABLISH_ERROR;
		return err;
    }

    /* Return the qdisc object to free memory resources */
    rtnl_qdisc_put(qdisc);
    return ECODTN_NET_TC_SUCCESS;
}


/*
* Function that adds a new filter and attach it to a hash table
*
*/
int u32_add_filter(struct nl_sock *sock, struct rtnl_link *rtnlLink, 
				   uint32_t prio, const char *keyval_str, const char *keymask_str, 
				   int keyoff, int keyoffmask, uint32_t parentMaj, 
			       uint32_t parentMin, uint32_t classfierMah, 
			       uint32_t classfierMin)
{
    int err;
    struct rtnl_cls *cls = (struct rtnl_cls *) rtnl_cls_alloc();

    if (!(cls)) {
        err = ECODTN_NET_TC_CLASSIFIER_ALLOC_ERROR;
		return err;
    }
    
    rtnl_tc_set_link(TC_CAST(cls), rtnlLink);

    if ((err = rtnl_tc_set_kind(TC_CAST(cls), "u32"))) {
        err = ECODTN_NET_TC_CLASSIFIER_SETUP_ERROR;
        return err;
    }

    rtnl_cls_set_prio(cls, prio);
    rtnl_cls_set_protocol(cls, ETH_P_IP);
    rtnl_tc_set_parent(TC_CAST(cls), TC_HANDLE(1, 0));

    uint32_t keyval = inet_network (keyval_str);
    printf("address 1: %u", keyval);
    uint32_t keymask = inet_network (keymask_str);

    err = rtnl_u32_add_key_uint32(cls, keyval, keymask, keyoff, keyoffmask); /* 10.0.0.0/8 */
    if (err < 0){
        err = ECODTN_NET_TC_CLASSIFIER_SETUP_ERROR;
        return err;
    }
    
    err = rtnl_u32_set_classid(cls, TC_HANDLE(parentMaj, parentMin));
    if (err < 0){        
		err = ECODTN_NET_TC_CLASSIFIER_SETUP_ERROR;
		return err;
    }
    
    if ((err = rtnl_cls_add(sock, cls, NLM_F_CREATE))) {
        err = ECODTN_NET_TC_CLASSIFIER_ESTABLISH_ERROR;
        return err;
    }
    rtnl_cls_put(cls);
    return ECODTN_NET_TC_SUCCESS;

}

/*
* Deletes an existent filter
*
*/
int u32_delete_filter(struct nl_sock *sock, struct rtnl_link *rtnlLink, 
				   uint32_t prio, const char *keyval_str, const char *keymask_str, 
				   int keyoff, int keyoffmask, uint32_t parentMaj, 
			       uint32_t parentMin, uint32_t classfierMah, uint32_t classfierMin )
{
    int err;
    struct rtnl_cls *cls = (struct rtnl_cls *) rtnl_cls_alloc();

    if (!(cls)) {
        err = ECODTN_NET_TC_CLASSIFIER_ALLOC_ERROR;
		return err;
    }
    
    rtnl_tc_set_link(TC_CAST(cls), rtnlLink);

    if ((err = rtnl_tc_set_kind(TC_CAST(cls), "u32"))) {
        err = ECODTN_NET_TC_CLASSIFIER_SETUP_ERROR;
        return err;
    }

    rtnl_cls_set_prio(cls, prio);
    rtnl_cls_set_protocol(cls, ETH_P_IP);
    rtnl_tc_set_parent(TC_CAST(cls), TC_HANDLE(parentMaj, parentMin));

    uint32_t keyval = inet_network (keyval_str);
    printf("address 1: %u", keyval);
    uint32_t keymask = inet_network (keymask_str);

    err = rtnl_u32_add_key_uint32(cls, keyval, keymask, keyoff, keyoffmask); /* 10.0.0.0/8 */
    if (err < 0){
        err = ECODTN_NET_TC_CLASSIFIER_SETUP_ERROR;
        return err;
    }
    
    err = rtnl_u32_set_classid(cls, TC_HANDLE(classfierMah, classfierMin));
    if (err < 0){        
		err = ECODTN_NET_TC_CLASSIFIER_SETUP_ERROR;
		return err;
    }
    
    if ((err = rtnl_cls_delete(sock, cls, 0))) {
        err = ECODTN_NET_TC_CLASSIFIER_ESTABLISH_ERROR;
        return err;
    }
    rtnl_cls_put(cls);
    return ECODTN_NET_TC_SUCCESS;

}

